### ISSUE TITLE
Quick clarification in README

### ISSUE THREAD

**Issue by ghost** [realdah/simple-json-replay-server#3]
Maybe make the README example more clear by changing:

`you can hit http://localhost:8008/test to see the result`

to

`you can hit http://localhost:8008/test?param1=value1%20to%20be%20matched&param2=value2%20to%20be%20matched to see the result`

**Comment by realdah** [comment]
Thanks for the suggestion, I have updated Readme document.

**Comment by realdah** [comment]
Meanwhile, I have updated a wiki to include some typical use cases that this tool can help.

https://github.com/realdah/simple-json-replay-server/wiki/Some-use-case-scenarios-for-demonstrating-how-to-use-this-tool

**Comment by realdah** [comment]
Taking issue to close.
