### ISSUE TITLE
Cookie support

### ISSUE THREAD

**Issue by manganc** [realdah/simple-json-replay-server#4]
Hi,

would it be possible to add cookie support to your mock server? I would like to have the mock service read a cookie and use as a signature to mock out a correct response based on data embedded in the cookie.

Thanks

**Comment by realdah** [comment]
Hi @manganc, my apologizes first, i mentioned that this mock server supports cookie filtering, but actually not.
I will implemented today/tomorrow.

**Comment by realdah** [comment]
added the cookie support, please let me know if it is working as expected.
