### ISSUE TITLE
When several paths are matched, the exact match does not take the precedence

### ISSUE THREAD

**Issue by ghost** [realdah/simple-json-replay-server#5]
Hello,

Given the 2 following json files, the exact path does not take the precedence if it was registered before:
an.example.query.json
{
    "request" : {
        "path": "testTest"
    },
    "response" : {
        "status" : 200,
        "data" : {
            "message" : "you can see this because you used the path 'testTest'"
        }
    }
}

example.query.json
{
    "request" : {
        "path": "test"
    },
    "response" : {
        "status" : 200,
        "data" : {
            "message" : "you get default result. let's try http://localhost:8008/test?aa=123 or http://localhost:8008/test?bb=123 to see what's happen"
        }
    }
}

When targetting localhost:4200/testTest, I would expect to get the response "you can see this because you used the path 'testTest'"", instead I receive "you get default result. let's try http://localhost:8008/test?aa=123 or http://localhost:8008/test?bb=123 to see what's happen".

It happens because the 2 paths are matched because on line#13 of match.js indexOf is used. Then there is no score on the path itself. Therefore the last one registered will be used.

One way to fix it would be to add a score when the path match exactly with the request.

Best Regards,
Kevin.

**Comment by realdah** [comment]
Sorry, just saw your issue ticket.
I will take a look on your PR, thanks!

**Comment by realdah** [comment]
@kferrier Thanks for the fix. I would like to share some of my views about your problem and solutions.

**Problem:**
If user defines some of the paths which shared the same string, they are  all considered as matched, thus, the exact matched one might has same or even lower weight score and failed to be picked up.

**Scenario 1**
for a given path  "location/listAll"
below paths are all matching with given path and sharing the same weight
- location
- list
- listAll

**Scenario 2**
for two given pathes "contact"  "adminContact"
if we config mock path as "contact", we will have the problem stated by you if the mock config order in specific way.  the "contact" path rule might being picked up when user accesses real path "adminContact" 

in this case, your solution makes 100% sense.

Let's take a look on 
**Scenario 3**
Again for two given pathes "contact/manage"  "adminContact/manage"
We will have exact same issue when we use mock path rule as "contact", it will pick up "adminContact/manage" path if mock data loaded with specific order too.

**However, in this case, your solution would not work any more.**

In this case, I think the **exact match** has to be changed to **regex match** the words between path delimiters "/".

**Comment by realdah** [comment]
Actually, we could enforce the rules to only match the whole word when comparing the path.
in this case, using path rule as "contact" would not match "adminContact" path any more.
and "contact" path rule should still match "contact/manage" or "manage/contact/list" paths etc.

And, in order to avoid breaking the existing users who accidentally configured partial word in path rule,  we can update the package version to 1.0.0 to avoid npm automatically install this change to existing customers.

See this article **Caret (^) and Tilde (~) in package.json**
[https://medium.com/@Hardy2151/caret-and-tilde-in-package-json-57f1cbbe347b](url)

**Comment by realdah** [comment]
actually, it is more complicated than I thought..

take one scenario:

if a real path like   "user/account/manage"

and then a mock file with a path as "user/account" should match this real path call.

in this case, we can't just match the whole word.

**Comment by realdah** [comment]
I feel that if we can support regex matching, that would solve all the problems we have.

**Comment by realdah** [comment]
I have merged your PR, thus close this ticket.
